### ISSUE TITLE
Grammar Error

### ISSUE THREAD

**Issue by CATower** [RikardFahlstrom/intro-data-capstone-musclehub#1]
In the third slide, "Chi Square tests was since we had categorical data," should be fixed.

**Comment by RikardFahlstrom** [comment]
@Codecademy-Chris I have attached an updated version
 with above issue fixed.

[Capstone Project Rikard Fahlström corrected.pdf](https://github.com/RikardFahlstrom/intro-data-capstone-musclehub/files/2776766/Capstone.Project.Rikard.Fahlstrom.corrected.pdf)

**Comment by CATower** [comment]
Okay great! We can close this issue.
